# Shield Chart: 0.10.0
# OCI Registry: jfrog.idonthaveany.boats
cluster_config:
  # REQUIRED - The name of the cluster
  name: "CHANGE_ME"
  # REQUIRED - Tags you want to apply to the metadata sent to the Sysdig Backend.
  tags:
    cluster: "CHANGE_ME"
    vz-vsadid: "CHANGE_ME"
    vz-vastid: "CHANGE_ME"

sysdig_endpoint:
  # REQUIRED IF NOT USING INSTALL.SH - The access key for the Sysdig Secure instance
  access_key:

host:
  priority_class:
    # OPTIONAL - The name of the priority class, typically system-node-critical
    name:

cluster:
  priority_class:
    # OPTIONAL - The name of the priority class, typically system-node-critical
    name:

proxy:
  # OPTIONAL - HTTP proxy to use for all HTTP requests
  http_proxy: ""
  # OPTIONAL - HTTPS proxy to use for all HTTPS requests
  https_proxy: ""
  # OPTIONAL - NO_PROXY comma delimited hosts and ips
  # If proxy is in use, exclude kubernetes cluster ip - kubectl get service kubernetes -o jsonpath='{.spec.clusterIP}'; echo 
  no_proxy: ""